# Generated by Django 6.1.1 on 2026-10-01 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('road', 'Road'), ('path', 'Path'), ('pedestrian_area', 'Pedestrian Area'), ('building', 'Building'), ('gate', 'Gate'), ('parking', 'Parking'), ('landmark', 'Landmark'), ('facility', 'Facility'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('geometry_data', models.JSONField()),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('osm', 'OpenStreetMap'), ('admin', 'Admin Editor'), ('survey', 'Campus Survey')], default='admin', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
