# Generated by Django 6.1.1 on 2026-10-01 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_id', models.CharField(db_index=True, max_length=255)),
                ('source', models.JSONField()),
                ('destination', models.JSONField()),
                ('current_position', models.JSONField(blank=True, null=True)),
                ('current_edge', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
