# Generated by Django 6.1.1 on 2026-10-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsession',
            name='current_eta_sec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='navigationsession',
            name='route_edges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='navigationsession',
            name='route_nodes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='navigationsession',
            name='destination',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='navigationsession',
            name='source',
            field=models.JSONField(default=dict),
        ),
    ]
