# Generated by Django 6.1.1 on 2026-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source', models.CharField(default='osm', max_length=50)),
                ('osm_id', models.CharField(blank=True, max_length=255)),
                ('nearest_graph_node', models.CharField(blank=True, max_length=255)),
                ('nearest_graph_distance_m', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
